app/src/main/java/org/qosp/notes/data/model/Note.kt, app/src/main/java/org/qosp/notes/data/sync/nextcloud/NextcloudManager.kt, app/src/main/java/org/qosp/notes/data/sync/nextcloud/model/NextcloudConverters.kt
This saves the tasks created in the app as :
```
```
This is further editable in the nextcloud notes web app which will be reflected on the Quillnote tasks
Fixes #146
=> Save tasks as Markdown note

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
If a tasked is un-checked, it goes back to its original position. The order is maintained in the Nextcloud notes too.
Fixes #186 and #197
=> Ticking off tasks moves them to the bottom.

app/build.gradle, app/src/main/java/org/qosp/notes/di/MarkwonModule.kt, app/src/main/res/values-night/themes.xml, app/src/main/res/values/attr.xml, app/src/main/res/values/themes.xml
Using the 'simple-ext' package was the easiest way I could implement the Highlight option. The other way would be to write a totally new plugin
Just followed the Docs for Markwon https://noties.io/Markwon/docs/v4/simple-ext/
Honestly I have no idea what I am doing with Kotlin, maybe someone can help improve this..? 
For #24
=> Added Highlight Text Span for "=="

app/src/main/java/org/qosp/notes/ui/about/AboutFragment.kt, app/src/main/res/layout/fragment_about.xml, app/src/main/res/values/no_translate_strings.xml
The version used be hardcoded in the XML. Now it is wired directly from build config
=> The version in About page 

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/editor/markdown/MarkdownUtils.kt, app/src/main/java/org/qosp/notes/ui/utils/views/ExtendedEditText.kt, gradle.properties
This finally fixes #39. The `enter` button is restored. It keeps the indentation of the previous line. It adds next list entry for regular, numbered and check list.
=> Automated list bullets

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
Demo:
Additionally there's a slight change in behaviour when user re-edits content of an untitled note.
Previously it would set focus to the title, but it seems to make more sense if focus is set to content in this case imo (seen at end of the gif).
But this can be reverted if wanted. :)
=> Fix #107 (display read/edit mode FAB also if note has empty title)

app/src/main/java/org/qosp/notes/preferences/AppPreferences.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceRepository.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorViewModel.kt, app/src/main/java/org/qosp/notes/ui/settings/SettingsFragment.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/menu/editor_top.xml, app/src/main/res/values/strings.xml
As mentioned in #118, this PR adds a user preference to either show the edit/view note button floating (as FAB, current state) or in the top menu, so users with smaller devices can use this option.
Default is show as FAB, so there's no change in default behaviour.
Demo:
=> Add preference to display edit/view note button either floating or in top bar

app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/java/org/qosp/notes/ui/deleted/DeletedFragment.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Fix #140: Correct misleading deletion messages when the "Delete notes in bin" option is set to "Never"

app/src/main/java/org/qosp/notes/ui/ActivityViewModel.kt, app/src/main/java/org/qosp/notes/ui/common/AbstractNotesFragment.kt, app/src/main/res/menu/main_selected_notes.xml
=> Add menu items to set compact/full preview for multiple selected notes at once

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
This PR fixes the order of tasks. When modifying (check/uncheck/text) a single task, all tasks are being reordered upon reopening the note. See #110 and #159 for more details on the problem.
Old logic (currently):
- when a task is modified (check/uncheck/text-change), reorder all tasks to their initial order but display done/checked tasks last
New logic (in PR):
- when a task is modified (text-change) only change the content of that task
- when a task is modified (check/uncheck)
- if the task is now done/checked move it to the very bottom
- if the task is now open/unchecked move it to after the last open task
Fixes #110 
Fixes #159
This is my first time contributing to Quillpad and to an Android App in general. So I'd appreciate it if you could have a look :)
=> Fix order of tasks in checklist

app/src/main/java/org/qosp/notes/preferences/AppPreferences.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceRepository.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorViewModel.kt, app/src/main/java/org/qosp/notes/ui/settings/SettingsFragment.kt, app/src/main/java/org/qosp/notes/ui/tasks/TasksAdapter.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/strings.xml
Demo (work in progress):
Currently it only changes the font size of the editor/view text, not sure if there should be seperate settings for e.g. preview font size or it should affect all text in the app (maybe too much work)?
And yes, imo it would be better to have a number (integer) text input (or e.g. a slider) instead of option (radio) buttons to set stepless font size, but I'm not capable of and won't do (but appreciate if someone wants to cooperate on this PR). :)   
related issues: #75, #99
=> Add Text editor/view font size preference

app/src/main/java/org/qosp/notes/ui/tasks/TasksAdapter.kt
If font size is not customized, fontSize=-1 so checkboxes are tiny in lists
=> Fix checkbox size when font size is not defined

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
Fixes #235
The fix (removal of the `if (!model.moveCheckedItems) return` line) was already submitted/merged in https://github.com/quillpad/quillpad/commit/90db9ff8933f0bd3338239fde92823bbcc6d50d7 but then seems it somehow got lost in https://github.com/quillpad/quillpad/commit/547a3e4543843df6aaf96da70cb58c57982bd853. 
This PR removes the line again restoring the original fix submitted by @fabix.
=> (Re-)Fix disappearing/not updating checklist entries (#235)

app/src/main/AndroidManifest.xml
Fixes #231
There's a (imo) bit confusing [topic](https://stackoverflow.com/questions/71031091/android-12-using-schedule-exact-alarm-permission-to-get-show-data-at-specific-t) about this on Stack Overflow saying that `permission.USE_EXACT_ALARM` is only allowed to use for e.g. calendar apps needing to exactly fire a user alarm/notification. Not sure if Quillpad qualifies for this.
=> Prevent crash caused by using SCHEDULE_EXACT_ALARM permission on Android 14+ (#231)

app/src/main/AndroidManifest.xml
Android 14 requires foreground services to declare types and declare appropriate permissions. While Quillpad defines the types, it doesn't declare the permissions. This commit adds the declarations.
This should, in theory, fix #266, but I haven't tested it as I kept getting Room errors (to clarify, the app was built, but crashed with an error about AppDatabase_impl when launched - I assume this is an issue with my configuration and not the commit).
=> Add permissions for foreground services on Android 14

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
closes #274
APKs for testing available here:
https://github.com/quillpad/quillpad/actions/runs/8988246519/artifacts/1480834695
=> Make cursor/focus default to note body (rather than note title) for new notes

app/src/main/java/org/qosp/notes/ui/sync/nextcloud/NextcloudAccountDialog.kt
closes #259
Demo:
Before this change, the toast would have shown only (imo rather unhelpful) `Something went wrong.` text.
=> Show original error message (rather than just 'Something went wrong') when Nextcloud sync fails to connect due to an unknown error

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/res/menu/editor_top.xml, app/src/main/res/values/strings.xml
This pull request adds an option for users to uncheck all items of the opened list-note at once. This is especially convenient when reusing an existing list, as it eliminates the need to manually uncheck each item of the list.
Fixes #176 
- When in editor view of a list-note, an option in the top-menu is added called "Uncheck all items". This option unchecks all items in the list of that note.
https://github.com/user-attachments/assets/1a5131b9-d0cf-489e-940f-9f2470822959
=> Uncheck all tasks functionality

app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
I had problems and spend a lot of time trying to get nextcloud sync working. I eventually found out that nextcloud notes need to be installed on the server and to improve the experience for other I've added this note: "Nextcloud Notes need to be installed on the Nextcloud Server or the Login will fail with "Something went wrong"!"
=> Add Note to Nextcloud sync settings that Nextcloud Notes need to be installes on the Server

app/src/main/java/org/qosp/notes/di/MarkwonModule.kt, app/src/main/java/org/qosp/notes/preferences/AppPreferences.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceRepository.kt, app/src/main/java/org/qosp/notes/ui/ActivityViewModel.kt, app/src/main/java/org/qosp/notes/ui/MainActivity.kt, app/src/main/java/org/qosp/notes/ui/attachments/recycler/AttachmentsPreviewGridManager.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/main/MainFragment.kt, app/src/main/java/org/qosp/notes/ui/notebooks/ManageNotebooksFragment.kt, app/src/main/java/org/qosp/notes/ui/notebooks/ManageNotebooksViewModel.kt, app/src/main/java/org/qosp/notes/ui/notebooks/NotebookFragment.kt, app/src/main/java/org/qosp/notes/ui/recorder/RecordAudioDialog.kt, app/src/main/java/org/qosp/notes/ui/settings/SettingsFragment.kt, app/src/main/java/org/qosp/notes/ui/tags/TagsFragment.kt, app/src/main/java/org/qosp/notes/ui/tags/TagsViewModel.kt, app/src/main/java/org/qosp/notes/ui/utils/coil/CoilImagesPlugin.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/menu/manage_notebooks.xml, app/src/main/res/menu/tags.xml, app/src/main/res/values/strings.xml
In this PR, I establish sorting functionality in notebook list as well as tag list. This PR might resolve #44, #77, and #184.
Highlights
-
First of all, I created two new settings context in the `AppPreference`: tag list sorting and navigation drawer's notebook sorting. (As seen in the attached screenshot.)
Next, I created the back-end to sort notebooks and tags by: alphabetical and creation date order (both ascending and descending). And since ****Quillnote**/Quillpad** does not yet store tag nor notebook creation date in the JSON schema, I use `tagId` and `notebookId` order to determine "creation date" order.
Finally, I added sorter button in both the "Manage Notebooks" menu and the tag list, so that the user does not need to open app's configuration in order to change sorting. …
=> Notebook and tag list sorter (#44, #77, and #184)

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/res/menu/editor_top.xml, app/src/main/res/values/strings.xml
This PR adds an option to the task menu which removes all tasks which have been checked.
This would close #160 and #329. Maybe #375 too, they mention #329 as a "similar issue", but I am not sure if it fits their use case or not.
Tell me if there is any problem with the implementation and I will gladly address it.
Great app, many thanks for maintaining it!
=> Add option to remove all checked tasks

app/src/androidTest/java/org/qosp/notes/di/TestUtilModule.kt, app/src/main/java/org/qosp/notes/di/UtilModule.kt, app/src/main/java/org/qosp/notes/ui/reminders/ReminderManager.kt
Currently, if there is no reminder title, the notification won't show any thing to help locate what it is about (can't open the note on my devices), and the bell icon and scheduled date time in the note are also cleaned up.
I'd like to suggest use the note title instead, if no reminder title. It is a easy fallback, and practical.
* Normally, the reminder is most likely with the same title. Repeat inputting isn't necessary.
* There is a default note title. People will change it to be meaningful if the note is important.
It's a kind of workaround for https://github.com/quillpad/quillpad/issues/87.
PS:
Don't know why, but the following doesn't work on my devices (Android 8 and 15). I'll try to do some research.
https://github.com/quillpad/quillpad/blob/5f7c84b20e32e6feadb68bd463aa0c8377bff61d …
=> Use the note title as a fallback for the reminder title

app/src/main/AndroidManifest.xml, app/src/main/java/org/qosp/notes/components/MediaStorageManager.kt, app/src/main/java/org/qosp/notes/ui/ActivityViewModel.kt, app/src/main/java/org/qosp/notes/ui/MainActivity.kt
The ability to share media from other apps is a feature I (and some others https://github.com/quillpad/quillpad/issues/352) would like to have. This change adds support to share single or multiple image, video or audio files to the app.
I'm not an Android dev, so I apologise in advance for any obvious mistakes, or if this is the wrong way to achieve this.  I hacked this together (with the help of GH copilot in full disclosure) and it seems to be functional.
Let me know if this is something your're interested in adding.
I'm happy to rework, or let someone who knows what they're doing do it correctly. 
Thanks for this awesome app!
=> Add support for shared media attachments

.editorconfig, app/build.gradle.kts, app/src/main/java/org/qosp/notes/data/repo/NoteRepository.kt, app/src/main/java/org/qosp/notes/data/repo/NoteRepositoryImpl.kt, app/src/main/java/org/qosp/notes/data/sync/core/SynchronizeNotes.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/qosp/notes/data/sync/core/SynchronizeNotesTest.kt
This commit addresses an issue where deleting a note on the remote server was incorrectly handled. Previously, the app would attempt to re-create the note remotely.
The fix ensures that if a local note has a corresponding remote mapping but the remote note is not found, a local delete action is triggered instead. This correctly reflects the remote deletion by moving the local note to the bin and removing its remote ID mapping.
Fixes #487
=> Fix note synchronization when a remote note is deleted.

app/src/main/java/org/qosp/notes/data/repo/NoteRepositoryImpl.kt, app/src/main/java/org/qosp/notes/data/sync/core/BackendProvider.kt
- Remove unnecessary `idMappingDao.deleteByLocalId` call in note repository logic.
- Fixes #495
=> Cleanup unused ID mapping in repositories
