app/build.gradle, app/src/main/res/values/no_translate_strings.xml, settings.gradle
=> 3 fix up ids

.github/workflows/android.yml, app/build.gradle
Updated the build file to not crunch PNG files
This closes #4
=> Add GitHub actions to build and release

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/editor/markdown/MarkdownUtils.kt, app/src/main/res/drawable/ic_highlight.xml, app/src/main/res/menu/editor_bottom.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
Markdown Highlight Option in order to address Issue #24  
This is not ready yet. Its missing the actual code to make the highlight.
=> Markdown Highlight Option

app/build.gradle, app/src/androidTest/java/org/qosp/notes/tests/BinCleaningWorkerTest.kt, app/src/main/java/org/qosp/notes/components/workers/BinCleaningWorker.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
=> Add 'Never' option to deleting notes from bin

.github/CONTRIBUTING.md, app/src/main/java/org/qosp/notes/ui/utils/ActivityResultUtils.kt, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/xml-v25/shortcuts.xml
Changed all the old references from Quillpad to quillnote
Fixes #100
=> quillpad-100 Backup file name is still Quillnote_backup

app/src/main/res/values-zh-rCN/strings.xml
Chinese Simplified translation
=> Add Chinese Simplified translations

app/src/main/res/values/colors.xml
=> Improved navigation bar

app/src/main/res/values-ru/strings.xml
Fixed incorrect translation of the option
=> fix ru translate

app/src/main/java/org/qosp/notes/ui/common/AbstractNotesFragment.kt
The syncs are on the background and do not show up on the UI. Fixes #137
=> quillpad-137 Sync happening too often

app/src/main/java/org/qosp/notes/preferences/AppPreferences.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt, app/src/main/java/org/qosp/notes/preferences/PreferenceRepository.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt, app/src/main/java/org/qosp/notes/ui/editor/EditorViewModel.kt, app/src/main/java/org/qosp/notes/ui/settings/SettingsFragment.kt, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Some people don't like that items move in the lists when there are (un)checked. This commit allows to choose.
=> Add a parameter to choose whether items are moved or not in lists when there are (un)checked

app/src/main/java/org/qosp/notes/preferences/PreferenceEnums.kt
Checked items move when checked
=> Restore the previous behavior as default one for checked items

app/src/main/res/values-night-v31/themes.xml, app/src/main/res/values-v31/themes.xml
Light mode of the material you colour scheme was broken, this fixes it.
=> Fix material you colour scheme light mode.

app/src/main/res/values-zh-rTW/no_translate_strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> Added zh-rTW directory

app/build.gradle, build.gradle, gradle/libs.versions.toml
From 21 to 24. Minimum supported android version is now Android 7.0
=> minSdk version upgrade

README.md, fastlane/metadata/android/en-US/full_description.txt
=> Document Nextcloud Notes app requirement for syncing

app/src/main/java/org/qosp/notes/ui/editor/EditorFragment.kt
Move new items to the top of checked as well, if respective option is enabled.
#319
=> Move new item to last unchecked if option is enabled

app/src/main/res/values-vi/strings.xml
=> Add Vietnamese

app/src/main/res/values-nl/strings.xml
This pull request adds the Dutch (nl) translation file with existing strings translated.
=> Add Dutch translation file

app/src/main/res/values-fr/strings.xml
The action new reminder had a typo in french here is the fix.
=> fix: typo in french

app/src/main/java/org/qosp/notes/ui/MainActivity.kt, app/src/main/java/org/qosp/notes/ui/launcher/WelcomePageData.kt, app/src/main/res/values/strings.xml
The app doesn't exit when pressing the back button. Fixes #401
=> Fix navigation back

app/src/main/res/values-de/strings.xml
* Reformat the file to match the English one.
* Improve some of the translations to sound more natural
* Fix some spelling mistakes
=> Update and improve German translations

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/res/xml/locales_config.xml
Allow users to change the app's language from the system settings. https://github.com/quillpad/quillpad/issues/16
=> Add support for Android system language selection

app/src/main/java/org/qosp/notes/ui/reminders/ReminderManager.kt
It works for me to solve https://github.com/quillpad/quillpad/pull/424#issuecomment-2854076064.
=> Ensure from the correct activity to open the note for a notification

README.md
Add widget that shows translation stats.
Closes #305
=> README.md Add link to Weblate

README.md
Removed anchor between app store badges.
Weblate widget moved to a separate line.
Sorry, I copied the widget and didn't checked in preview how it looks
=> README.md fix formatting
